name: Test
on: 
  push:
  workflow_dispatch:

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0
      - name: Test zig build c
        run: |
          zig build run -Dexe_is_cpp=False
      - name: Test gcc build cpp
        run: |
          ./gcc_build.sh
      - name: Test zig build cpp
        run: |
          zig build run -Dexe_is_cpp=True
